-- AlterTable
ALTER TABLE "idoso" ALTER COLUMN "naturalidade" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "estado_civil" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "religiao" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "escolaridade" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "rg" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "rg_orgao_expedidor" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "certidao_nascimento_folha" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "certidao_nascimento_livro" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "certidao_casamento_folha" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "certidao_casamento_livro" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "motivo_inativacao" SET DATA TYPE VARCHAR,
ALTER COLUMN "cartao_sus" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "cidade" SET DATA TYPE VARCHAR(255);
